# Configuration file for NEH OPCPA lasers

main:
    xpm_pv: "DAQ:NEH:XPM:0:SEQCODES"
    title: "NEH Laser Hall OPCPA Rep. Rate Configuration"

lasers:
  # TODO: add inclusivity PV
  bay_2:

    laser_desc: "Bay 2 TPR Configuration"

    tpr_base: "LAS:LHN:TPR:02"

    # TPR Channels
    channels:
      ch0:
        desc: "Carbide Goose"
        ch: "00"
      ch1:
        desc: "Carbide"
        ch: "01"
      ch2:
        desc: "Amphos Goose"
        ch: "02"
      ch3:
        desc: "Amphos Base"
        ch: "03"
      ch4:
        desc: "Carbide PP Goose"
        ch: "04"
      ch5:
        desc: "Carbide PP"
        ch: "05"
      ch6:
        desc: "TIC Stop Trigger"
        ch: "06"

    # Reprate (in TPG seconds) to event code mapping for the system
    rep_rates:
      130: 256
      260: 257
      650: 258
      1300: 259
      2500: 260
      6500: 261
      8125: 262
      16250: 263
      32500: 264
      910000: 265

    # Allowed rep-rate configs (in TPG seconds) for the given laser
    rate_configs:
      cfg_130:
        rate: "130 Hz"
        ch4:
          ratemode: "Seq"
          rate: 130
          enable: "Enabled"
        ch5:
          ratemode: "Seq"
          rate: 130
          enable: "Enabled"

      cfg_260:
        rate: "260 Hz"
        ch4:
          ratemode: "Seq"
          rate: 260
          enable: "Enabled"
        ch5:
          ratemode: "Seq"
          rate: 260
          enable: "Enabled"

      cfg_650:
        rate: "650 Hz"
        ch4:
          ratemode: "Seq"
          rate: 650
          enable: "Enabled"
        ch5:
          ratemode: "Seq"
          rate: 650
          enable: "Enabled"

      cfg_1300:
        rate: "1300 Hz"
        ch4:
          ratemode: "Seq"
          rate: 1300
          enable: "Enabled"
        ch5:
          ratemode: "Seq"
          rate: 1300
          enable: "Enabled"

      cfg_32500:
        rate: "32500 Hz"
        ch4:
          ratemode: "Seq"
          rate: 32500
          enable: "Enabled"
        ch5:
          ratemode: "Seq"
          rate: 32500
          enable: "Enabled"
