# Configuration file for NEH OPCPA lasers

main:
    xpm_pv: "DAQ:NEH:XPM:0:SEQCODES"
    title: "NEH Laser Hall OPCPA Rep. Rate Configuration"

lasers:
  bay_2:

    laser_desc: "Bay 2 TPR Configuration"

    laser_database: "db.json"

    # TPR Channels
    devices:
      Carbide_Goose:
        rbvs: ["name", "eventrate", "ratemode", "seqcode", "width_setpoint", "delay_setpoint", "operation", "enable_ch_cmd"]
        show: True
      Carbide_Base:
        rbvs: ["name", "eventrate", "ratemode", "seqcode", "width_setpoint", "delay_setpoint", "operation", "enable_ch_cmd"]
        show: True
      Amphos_Goose:
        rbvs: ["name", "eventrate", "ratemode", "seqcode", "width_setpoint", "delay_setpoint", "operation", "enable_ch_cmd"]
        show: True
      Amphos_Base:
        rbvs: ["name", "eventrate", "ratemode", "seqcode", "width_setpoint", "delay_setpoint", "operation", "enable_ch_cmd"]
        show: True
      Carbide_PP_Goose:
        rbvs: ["name", "eventrate", "ratemode", "seqcode", "width_setpoint", "delay_setpoint", "operation", "enable_ch_cmd"]
        show: True
      Carbide_PP:
        rbvs: ["name", "eventrate", "ratemode", "seqcode", "width_setpoint", "delay_setpoint", "operation", "enable_ch_cmd"]
        show: True
      TIC_Stop:
        rbvs: ["name", "eventrate", "ratemode", "seqcode", "width_setpoint", "delay_setpoint", "operation", "enable_ch_cmd"]
        show: True
      TIC_Gate:
        rbvs: ["name", "eventrate", "ratemode", "seqcode", "width_setpoint", "delay_setpoint", "operation", "enable_ch_cmd"]
        show: True
      Tstsig:
        rbvs: ["name", "val"]
        show: True


    # Allowed rep-rate configs (in TPG seconds) for the given laser
    laser_rate_configs:
      desc: "Base Rep. Rate"
      cfg_130:
        desc: "130 Hz"
        Carbide_PP_Goose:
          ratemode: "Seq"
          seqcode: 256
          enable_trg_cmd: "Enabled"
          enable_ch_cmd: "Enabled"
        Carbide_PP:
          ratemode: "Seq"
          seqcode: 256
          enable_trg_cmd: "Enabled"
          enable_ch_cmd: "Enabled"
        TIC_Gate:
          ratemode: "Seq"
          seqcode: 256
          enable_trg_cmd: "Enabled"
          enable_ch_cmd: "Enabled"

      cfg_500:
        desc: "500 Hz"
        Carbide_PP_Goose:
          ratemode: "Seq"
          seqcode: 257
          enable_trg_cmd: "Enabled"
          enable_ch_cmd: "Enabled"
        Carbide_PP:
          ratemode: "Seq"
          seqcode: 257
          enable_trg_cmd: "Enabled"
          enable_ch_cmd: "Enabled"
        TIC_Gate:
          ratemode: "Seq"
          seqcode: 257
          enable_trg_cmd: "Enabled"
          enable_ch_cmd: "Enabled"

      cfg_650:
        desc: "650 Hz"
        Carbide_PP_Goose:
          ratemode: "Seq"
          seqcode: 258
          enable_trg_cmd: "Enabled"
          enable_ch_cmd: "Enabled"
        Carbide_PP:
          ratemode: "Seq"
          seqcode: 258
          enable_trg_cmd: "Enabled"
          enable_ch_cmd: "Enabled"
        TIC_Gate:
          ratemode: "Seq"
          seqcode: 258
          enable_trg_cmd: "Enabled"
          enable_ch_cmd: "Enabled"

      cfg_1300:
        desc: "1300 Hz"
        Carbide_PP_Goose:
          ratemode: "Seq"
          seqcode: 259
          enable_trg_cmd: "Enabled"
          enable_ch_cmd: "Enabled"
        Carbide_PP:
          ratemode: "Seq"
          seqcode: 259
          enable_trg_cmd: "Enabled"
          enable_ch_cmd: "Enabled"
        TIC_Gate:
          ratemode: "Seq"
          seqcode: 259
          enable_trg_cmd: "Enabled"
          enable_ch_cmd: "Enabled"

      cfg_2500:
        desc: "2500 Hz"
        Carbide_PP_Goose:
          ratemode: "Seq"
          seqcode: 260
          enable_trg_cmd: "Enabled"
          enable_ch_cmd: "Enabled"
        Carbide_PP:
          ratemode: "Seq"
          seqcode: 260
          enable_trg_cmd: "Enabled"
          enable_ch_cmd: "Enabled"
        TIC_Gate:
          ratemode: "Seq"
          seqcode: 260
          enable_trg_cmd: "Enabled"
          enable_ch_cmd: "Enabled"

      cfg_8125:
        desc: "8125 Hz"
        Carbide_PP_Goose:
          ratemode: "Seq"
          seqcode: 261
          enable_trg_cmd: "Enabled"
          enable_ch_cmd: "Enabled"
        Carbide_PP:
          ratemode: "Seq"
          seqcode: 261
          enable_trg_cmd: "Enabled"
          enable_ch_cmd: "Enabled"
        TIC_Gate:
          ratemode: "Seq"
          seqcode: 261
          enable_trg_cmd: "Enabled"
          enable_ch_cmd: "Enabled"

      cfg_32500:
        desc: "32500 Hz"
        Carbide_PP_Goose:
          ratemode: "Seq"
          seqcode: 262
          enable_trg_cmd: "Enabled"
          enable_ch_cmd: "Enabled"
        Carbide_PP:
          ratemode: "Seq"
          seqcode: 262
          enable_trg_cmd: "Enabled"
          enable_ch_cmd: "Enabled"
        TIC_Gate:
          ratemode: "Seq"
          seqcode: 262
          enable_trg_cmd: "Enabled"
          enable_ch_cmd: "Enabled"

    # Allowed goose configs (in TPG seconds) for the given laser
    goose_rate_configs:
      desc: "Goose Rep. Rate"
      cfg_goose_4:
        desc: "4 Hz Goose"
        Carbide_Goose:
          ratemode: "Seq"
          seqcode: 264
          polarity: 0
          enable_trg_cmd: "Enabled"
          enable_ch_cmd: "Enabled"
          width_setpoint: 15.4
        Carbide_Base:
          operation: "AND"
        Amphos_Goose:
          ratemode: "Seq"
          seqcode: 264
          polarity: 0
          enable_trg_cmd: "Enabled"
          enable_ch_cmd: "Enabled"
          width_setpoint: 15.4
        Amphos_Base:
          operation: "AND"
        Carbide_PP_Goose:
          ratemode: "Seq"
          seqcode: 264
          polarity: 0
          enable_trg_cmd: "Enabled"
          enable_ch_cmd: "Enabled"
          width_setpoint: 15.4
        Carbide_PP:
          operation: "AND"
        TIC_Gate:
          ratemode: "Seq"
          seqcode: 264
          enable_trg_cmd: "Enabled"
          enable_ch_cmd: "Enabled"

      cfg_goose_40:
        desc: "40 Hz Goose"
        Carbide_Goose:
          ratemode: "Seq"
          seqcode: 265
          polarity: 0
          enable_trg_cmd: "Enabled"
          enable_ch_cmd: "Enabled"
          width_setpoint: 15.4
        Carbide_Base:
          operation: "AND"
        Amphos_Goose:
          ratemode: "Seq"
          seqcode: 265
          polarity: 0
          enable_trg_cmd: "Enabled"
          enable_ch_cmd: "Enabled"
          width_setpoint: 15.4
        Amphos_Base:
          operation: "AND"
        Carbide_PP_Goose:
          ratemode: "Seq"
          seqcode: 265
          polarity: 0
          enable_trg_cmd: "Enabled"
          enable_ch_cmd: "Enabled"
          width_setpoint: 15.4
        Carbide_PP:
          operation: "AND"
        TIC_Gate:
          ratemode: "Seq"
          seqcode: 265
          enable_trg_cmd: "Enabled"
          enable_ch_cmd: "Enabled"

      cfg_goose_50:
        desc: "50 Hz Goose"
        Carbide_Goose:
          ratemode: "Seq"
          seqcode: 266
          polarity: 0
          enable_trg_cmd: "Enabled"
          enable_ch_cmd: "Enabled"
          width_setpoint: 15.4
        Carbide_Base:
          operation: "AND"
        Amphos_Goose:
          ratemode: "Seq"
          seqcode: 266
          polarity: 0
          enable_trg_cmd: "Enabled"
          enable_ch_cmd: "Enabled"
          width_setpoint: 15.4
        Amphos_Base:
          operation: "AND"
        Carbide_PP_Goose:
          ratemode: "Seq"
          seqcode: 266
          polarity: 0
          enable_trg_cmd: "Enabled"
          enable_ch_cmd: "Enabled"
          width_setpoint: 15.4
        Carbide_PP:
          operation: "AND"
        TIC_Gate:
          ratemode: "Seq"
          seqcode: 266
          enable_trg_cmd: "Enabled"
          enable_ch_cmd: "Enabled"

      cfg_goose_250:
        desc: "250 Hz Goose"
        Carbide_Goose:
          ratemode: "Seq"
          seqcode: 267
          polarity: 0
          enable_trg_cmd: "Enabled"
          enable_ch_cmd: "Enabled"
          width_setpoint: 15.4
        Carbide_Base:
          operation: "AND"
        Amphos_Goose:
          ratemode: "Seq"
          seqcode: 267
          polarity: 0
          enable_trg_cmd: "Enabled"
          enable_ch_cmd: "Enabled"
          width_setpoint: 15.4
        Amphos_Base:
          operation: "AND"
        Carbide_PP_Goose:
          ratemode: "Seq"
          seqcode: 267
          polarity: 0
          enable_trg_cmd: "Enabled"
          enable_ch_cmd: "Enabled"
        Carbide_PP:
          operation: "AND"
        TIC_Gate:
          ratemode: "Seq"
          seqcode: 267
          enable_trg_cmd: "Enabled"
          enable_ch_cmd: "Enabled"

      cfg_goose_off:
        desc: "Goose off"
        Carbide_Base:
          operation: "NOOP"
        Amphos_Base:
          operation: "NOOP"
        Carbide_PP:
          operation: "NOOP"

    goose_arrival_configs:
      desc: "Goose Arrival"
      cfg_early:
        desc: "Early"
        Carbide_Goose:
          polarity: 1
          width_setpoint: 30.8
        Amphos_Goose:
          polarity: 1
          width_setpoint: 30.8
        Carbide_PP_Goose:
          polarity: 1
          width_setpoint: 30.8
      cfg_late:
        desc: "Late"
        Carbide_Goose:
          polarity: 0
          width_setpoint: 15.4
        Amphos_Goose:
          polarity: 0
          width_setpoint: 15.4
        Carbide_PP_Goose:
          polarity: 0
          width_setpoint: 15.4

#  bay_3:
#
#    laser_desc: "Bay 3 TPR Configuration"
#
#    tpr_base: "LAS:LHN:TPR:01"
#
#    # TPR Channels
#    channels:
#      Carbide_Goose:
#        desc: "Carbide Goose"
#        ch: "00"
#        show: True
#      Carbide_Base:
#        desc: "Carbide"
#        ch: "01"
#        show: True
#      Amphos_Goose:
#        desc: "Amphos Goose"
#        ch: "02"
#        show: True
#      Amphos_Base:
#        desc: "Amphos Base"
#        ch: "03"
#        show: True
#      Carbide_PP:_Goose
#        desc: "Carbide PP Goose"
#        ch: "04"
#        show: True
#      Carbide_PP:
#        desc: "Carbide PP"
#        ch: "05"
#        show: True
#      ch6:
#        desc: "TIC Stop Trigger"
#        ch: "06"
#        show: True
#      TIC_Gate:
#        desc: "TIC Gate Trigger"
#        ch: "07"
#        show: True
#
#    # Allowed rep-rate configs (in TPG seconds) for the given laser
#    rate_configs:
#      cfg_130:
#        desc: "130 Hz"
#        Carbide_PP:_Goose
#          ratemode: "Seq"
#          seqcode: 256
#          enable_trg_cmd: "Enabled"
#          enable_ch_cmd: "Enabled"
#        Carbide_PP:
#          ratemode: "Seq"
#          seqcode: 256
#          enable_trg_cmd: "Enabled"
#          enable_ch_cmd: "Enabled"
#        TIC_Gate:
#          ratemode: "Seq"
#          seqcode: 256
#          enable_trg_cmd: "Enabled"
#          enable_ch_cmd: "Enabled"
#
#      cfg_500:
#        desc: "500 Hz"
#        Carbide_PP:_Goose
#          ratemode: "Seq"
#          seqcode: 257
#          enable_trg_cmd: "Enabled"
#          enable_ch_cmd: "Enabled"
#        Carbide_PP:
#          ratemode: "Seq"
#          seqcode: 257
#          enable_trg_cmd: "Enabled"
#          enable_ch_cmd: "Enabled"
#        TIC_Gate:
#          ratemode: "Seq"
#          seqcode: 257
#          enable_trg_cmd: "Enabled"
#          enable_ch_cmd: "Enabled"
#
#      cfg_650:
#        desc: "650 Hz"
#        Carbide_PP:_Goose
#          ratemode: "Seq"
#          seqcode: 258
#          enable_trg_cmd: "Enabled"
#          enable_ch_cmd: "Enabled"
#        Carbide_PP:
#          ratemode: "Seq"
#          seqcode: 258
#          enable_trg_cmd: "Enabled"
#          enable_ch_cmd: "Enabled"
#        TIC_Gate:
#          ratemode: "Seq"
#          seqcode: 258
#          enable_trg_cmd: "Enabled"
#          enable_ch_cmd: "Enabled"
#
#      cfg_1300:
#        desc: "1300 Hz"
#        Carbide_PP:_Goose
#          ratemode: "Seq"
#          seqcode: 259
#          enable_trg_cmd: "Enabled"
#          enable_ch_cmd: "Enabled"
#        Carbide_PP:
#          ratemode: "Seq"
#          seqcode: 259
#          enable_trg_cmd: "Enabled"
#          enable_ch_cmd: "Enabled"
#        TIC_Gate:
#          ratemode: "Seq"
#          seqcode: 259
#          enable_trg_cmd: "Enabled"
#          enable_ch_cmd: "Enabled"
#
#      cfg_2500:
#        desc: "2500 Hz"
#        Carbide_PP:_Goose
#          ratemode: "Seq"
#          seqcode: 260
#          enable_trg_cmd: "Enabled"
#          enable_ch_cmd: "Enabled"
#        Carbide_PP:
#          ratemode: "Seq"
#          seqcode: 260
#          enable_trg_cmd: "Enabled"
#          enable_ch_cmd: "Enabled"
#        TIC_Gate:
#          ratemode: "Seq"
#          seqcode: 260
#          enable_trg_cmd: "Enabled"
#          enable_ch_cmd: "Enabled"
#
#      cfg_8125:
#        desc: "8125 Hz"
#        Carbide_PP:_Goose
#          ratemode: "Seq"
#          seqcode: 261
#          enable_trg_cmd: "Enabled"
#          enable_ch_cmd: "Enabled"
#        Carbide_PP:
#          ratemode: "Seq"
#          seqcode: 261
#          enable_trg_cmd: "Enabled"
#          enable_ch_cmd: "Enabled"
#        TIC_Gate:
#          ratemode: "Seq"
#          seqcode: 261
#          enable_trg_cmd: "Enabled"
#          enable_ch_cmd: "Enabled"
#
#      cfg_32500:
#        desc: "32500 Hz"
#        Carbide_PP:_Goose
#          ratemode: "Seq"
#          seqcode: 262
#          enable_trg_cmd: "Enabled"
#          enable_ch_cmd: "Enabled"
#        Carbide_PP:
#          ratemode: "Seq"
#          seqcode: 262
#          enable_trg_cmd: "Enabled"
#          enable_ch_cmd: "Enabled"
#        TIC_Gate:
#          ratemode: "Seq"
#          seqcode: 262
#          enable_trg_cmd: "Enabled"
#          enable_ch_cmd: "Enabled"
#
#      cfg_goose_4:
#        desc: "4 Hz Goose"
#        Carbide_Goose:
#          ratemode: "Seq"
#          seqcode: 264
#          polarity: 0
#          enable_trg_cmd: "Enabled"
#          enable_ch_cmd: "Enabled"
#          width_setpoint: 15.4
#        Carbide_Base:
#          operation: "AND"
#        Amphos_Goose:
#          ratemode: "Seq"
#          seqcode: 264
#          polarity: 0
#          enable_trg_cmd: "Enabled"
#          enable_ch_cmd: "Enabled"
#          width_setpoint: 15.4
#        Amphos_Base:
#          operation: "AND"
#        Carbide_PP:_Goose
#          ratemode: "Seq"
#          seqcode: 264
#          polarity: 0
#          enable_trg_cmd: "Enabled"
#          enable_ch_cmd: "Enabled"
#          width_setpoint: 15.4
#        Carbide_PP:
#          operation: "AND"
#        TIC_Gate:
#          ratemode: "Seq"
#          seqcode: 264
#          enable_trg_cmd: "Enabled"
#          enable_ch_cmd: "Enabled"
#
#      cfg_goose_40:
#        desc: "40 Hz Goose"
#        Carbide_Goose:
#          ratemode: "Seq"
#          seqcode: 265
#          polarity: 0
#          enable_trg_cmd: "Enabled"
#          enable_ch_cmd: "Enabled"
#          width_setpoint: 15.4
#        Carbide_Base:
#          operation: "AND"
#        Amphos_Goose:
#          ratemode: "Seq"
#          seqcode: 265
#          polarity: 0
#          enable_trg_cmd: "Enabled"
#          enable_ch_cmd: "Enabled"
#          width_setpoint: 15.4
#        Amphos_Base:
#          operation: "AND"
#        Carbide_PP:_Goose
#          ratemode: "Seq"
#          seqcode: 265
#          polarity: 0
#          enable_trg_cmd: "Enabled"
#          enable_ch_cmd: "Enabled"
#          width_setpoint: 15.4
#        Carbide_PP:
#          operation: "AND"
#        TIC_Gate:
#          ratemode: "Seq"
#          seqcode: 265
#          enable_trg_cmd: "Enabled"
#          enable_ch_cmd: "Enabled"
#
#      cfg_goose_50:
#        desc: "50 Hz Goose"
#        Carbide_Goose:
#          ratemode: "Seq"
#          seqcode: 266
#          polarity: 0
#          enable_trg_cmd: "Enabled"
#          enable_ch_cmd: "Enabled"
#          width_setpoint: 15.4
#        Carbide_Base:
#          operation: "AND"
#        Amphos_Goose:
#          ratemode: "Seq"
#          seqcode: 266
#          polarity: 0
#          enable_trg_cmd: "Enabled"
#          enable_ch_cmd: "Enabled"
#          width_setpoint: 15.4
#        Amphos_Base:
#          operation: "AND"
#        Carbide_PP:_Goose
#          ratemode: "Seq"
#          seqcode: 266
#          polarity: 0
#          enable_trg_cmd: "Enabled"
#          enable_ch_cmd: "Enabled"
#          width_setpoint: 15.4
#        Carbide_PP:
#          operation: "AND"
#        TIC_Gate:
#          ratemode: "Seq"
#          seqcode: 266
#          enable_trg_cmd: "Enabled"
#          enable_ch_cmd: "Enabled"
#
#      cfg_goose_250:
#        desc: "250 Hz Goose"
#        Carbide_Goose:
#          ratemode: "Seq"
#          seqcode: 267
#          polarity: 0
#          enable_trg_cmd: "Enabled"
#          enable_ch_cmd: "Enabled"
#          width_setpoint: 15.4
#        Carbide_Base:
#          operation: "AND"
#        Amphos_Goose:
#          ratemode: "Seq"
#          seqcode: 267
#          polarity: 0
#          enable_trg_cmd: "Enabled"
#          enable_ch_cmd: "Enabled"
#          width_setpoint: 15.4
#        Amphos_Base:
#          operation: "AND"
#        Carbide_PP:_Goose
#          ratemode: "Seq"
#          seqcode: 267
#          polarity: 0
#          enable_trg_cmd: "Enabled"
#          enable_ch_cmd: "Enabled"
#          width_setpoint: 15.4
#        Carbide_PP:
#          operation: "AND"
#        TIC_Gate:
#          ratemode: "Seq"
#          seqcode: 267
#          enable_trg_cmd: "Enabled"
#          enable_ch_cmd: "Enabled"
#
#      cfg_goose_off:
#        desc: "Goose off"
#        Carbide_Base:
#          operation: "NOOP"
#        Amphos_Base:
#          operation: "NOOP"
#        Carbide_PP:
#          operation: "NOOP"
