# Configuration file for NEH OPCPA lasers

main:
    xpm_pv: "DAQ:NEH:XPM:0:SEQCODES"
    title: "NEH Laser Hall OPCPA Rep. Rate Configuration"

lasers:
  bay_2:

    laser_desc: "Bay 2 TPR Configuration"

    tpr_base: "LAS:LHN:TPR:02"

    # TPR Channels
    channels:
      ch0:
        desc: "Carbide Goose"
        ch: "00"
        show: True
      ch1:
        desc: "Carbide"
        ch: "01"
        show: True
      ch2:
        desc: "Amphos Goose"
        ch: "02"
        show: True
      ch3:
        desc: "Amphos Base"
        ch: "03"
        show: True
      ch4:
        desc: "Carbide PP Goose"
        ch: "04"
        show: True
      ch5:
        desc: "Carbide PP"
        ch: "05"
        show: True
      ch6:
        desc: "TIC Stop Trigger"
        ch: "06"
        show: True
      ch7:
        desc: "TIC Gate Trigger"
        ch: "07"
        show: True

    # Allowed rep-rate configs (in TPG seconds) for the given laser
    laser_rate_configs:
      desc: "Base Rep. Rate"
      cfg_130:
        desc: "130 Hz"
        ch4:
          ratemode: "Seq"
          seqcode: 256
          enable_trg_cmd: "Enabled"
          enable_ch_cmd: "Enabled"
        ch5:
          ratemode: "Seq"
          seqcode: 256
          enable_trg_cmd: "Enabled"
          enable_ch_cmd: "Enabled"
        ch7:
          ratemode: "Seq"
          seqcode: 256
          enable_trg_cmd: "Enabled"
          enable_ch_cmd: "Enabled"

      cfg_500:
        desc: "500 Hz"
        ch4:
          ratemode: "Seq"
          seqcode: 257
          enable_trg_cmd: "Enabled"
          enable_ch_cmd: "Enabled"
        ch5:
          ratemode: "Seq"
          seqcode: 257
          enable_trg_cmd: "Enabled"
          enable_ch_cmd: "Enabled"
        ch7:
          ratemode: "Seq"
          seqcode: 257
          enable_trg_cmd: "Enabled"
          enable_ch_cmd: "Enabled"

      cfg_650:
        desc: "650 Hz"
        ch4:
          ratemode: "Seq"
          seqcode: 258
          enable_trg_cmd: "Enabled"
          enable_ch_cmd: "Enabled"
        ch5:
          ratemode: "Seq"
          seqcode: 258
          enable_trg_cmd: "Enabled"
          enable_ch_cmd: "Enabled"
        ch7:
          ratemode: "Seq"
          seqcode: 258
          enable_trg_cmd: "Enabled"
          enable_ch_cmd: "Enabled"

      cfg_1300:
        desc: "1300 Hz"
        ch4:
          ratemode: "Seq"
          seqcode: 259
          enable_trg_cmd: "Enabled"
          enable_ch_cmd: "Enabled"
        ch5:
          ratemode: "Seq"
          seqcode: 259
          enable_trg_cmd: "Enabled"
          enable_ch_cmd: "Enabled"
        ch7:
          ratemode: "Seq"
          seqcode: 259
          enable_trg_cmd: "Enabled"
          enable_ch_cmd: "Enabled"

      cfg_2500:
        desc: "2500 Hz"
        ch4:
          ratemode: "Seq"
          seqcode: 260
          enable_trg_cmd: "Enabled"
          enable_ch_cmd: "Enabled"
        ch5:
          ratemode: "Seq"
          seqcode: 260
          enable_trg_cmd: "Enabled"
          enable_ch_cmd: "Enabled"
        ch7:
          ratemode: "Seq"
          seqcode: 260
          enable_trg_cmd: "Enabled"
          enable_ch_cmd: "Enabled"

      cfg_8125:
        desc: "8125 Hz"
        ch4:
          ratemode: "Seq"
          seqcode: 261
          enable_trg_cmd: "Enabled"
          enable_ch_cmd: "Enabled"
        ch5:
          ratemode: "Seq"
          seqcode: 261
          enable_trg_cmd: "Enabled"
          enable_ch_cmd: "Enabled"
        ch7:
          ratemode: "Seq"
          seqcode: 261
          enable_trg_cmd: "Enabled"
          enable_ch_cmd: "Enabled"

      cfg_32500:
        desc: "32500 Hz"
        ch4:
          ratemode: "Seq"
          seqcode: 262
          enable_trg_cmd: "Enabled"
          enable_ch_cmd: "Enabled"
        ch5:
          ratemode: "Seq"
          seqcode: 262
          enable_trg_cmd: "Enabled"
          enable_ch_cmd: "Enabled"
        ch7:
          ratemode: "Seq"
          seqcode: 262
          enable_trg_cmd: "Enabled"
          enable_ch_cmd: "Enabled"

    # Allowed goose configs (in TPG seconds) for the given laser
    goose_rate_configs:
      desc: "Goose Rep. Rate"
      cfg_goose_4:
        desc: "4 Hz Goose"
        ch0:
          ratemode: "Seq"
          seqcode: 264
          polarity: 0
          enable_trg_cmd: "Enabled"
          enable_ch_cmd: "Enabled"
          width_setpoint: 15.4
        ch1:
          operation: "AND"
        ch2:
          ratemode: "Seq"
          seqcode: 264
          polarity: 0
          enable_trg_cmd: "Enabled"
          enable_ch_cmd: "Enabled"
          width_setpoint: 15.4
        ch3:
          operation: "AND"
        ch4:
          ratemode: "Seq"
          seqcode: 264
          polarity: 0
          enable_trg_cmd: "Enabled"
          enable_ch_cmd: "Enabled"
          width_setpoint: 15.4
        ch5:
          operation: "AND"
        ch7:
          ratemode: "Seq"
          seqcode: 264
          enable_trg_cmd: "Enabled"
          enable_ch_cmd: "Enabled"

      cfg_goose_40:
        desc: "40 Hz Goose"
        ch0:
          ratemode: "Seq"
          seqcode: 265
          polarity: 0
          enable_trg_cmd: "Enabled"
          enable_ch_cmd: "Enabled"
          width_setpoint: 15.4
        ch1:
          operation: "AND"
        ch2:
          ratemode: "Seq"
          seqcode: 265
          polarity: 0
          enable_trg_cmd: "Enabled"
          enable_ch_cmd: "Enabled"
          width_setpoint: 15.4
        ch3:
          operation: "AND"
        ch4:
          ratemode: "Seq"
          seqcode: 265
          polarity: 0
          enable_trg_cmd: "Enabled"
          enable_ch_cmd: "Enabled"
          width_setpoint: 15.4
        ch5:
          operation: "AND"
        ch7:
          ratemode: "Seq"
          seqcode: 265
          enable_trg_cmd: "Enabled"
          enable_ch_cmd: "Enabled"

      cfg_goose_50:
        desc: "50 Hz Goose"
        ch0:
          ratemode: "Seq"
          seqcode: 266
          polarity: 0
          enable_trg_cmd: "Enabled"
          enable_ch_cmd: "Enabled"
          width_setpoint: 15.4
        ch1:
          operation: "AND"
        ch2:
          ratemode: "Seq"
          seqcode: 266
          polarity: 0
          enable_trg_cmd: "Enabled"
          enable_ch_cmd: "Enabled"
          width_setpoint: 15.4
        ch3:
          operation: "AND"
        ch4:
          ratemode: "Seq"
          seqcode: 266
          polarity: 0
          enable_trg_cmd: "Enabled"
          enable_ch_cmd: "Enabled"
          width_setpoint: 15.4
        ch5:
          operation: "AND"
        ch7:
          ratemode: "Seq"
          seqcode: 266
          enable_trg_cmd: "Enabled"
          enable_ch_cmd: "Enabled"

      cfg_goose_250:
        desc: "250 Hz Goose"
        ch0:
          ratemode: "Seq"
          seqcode: 267
          polarity: 0
          enable_trg_cmd: "Enabled"
          enable_ch_cmd: "Enabled"
          width_setpoint: 15.4
        ch1:
          operation: "AND"
        ch2:
          ratemode: "Seq"
          seqcode: 267
          polarity: 0
          enable_trg_cmd: "Enabled"
          enable_ch_cmd: "Enabled"
          width_setpoint: 15.4
        ch3:
          operation: "AND"
        ch4:
          ratemode: "Seq"
          seqcode: 267
          polarity: 0
          enable_trg_cmd: "Enabled"
          enable_ch_cmd: "Enabled"
        ch5:
          operation: "AND"
        ch7:
          ratemode: "Seq"
          seqcode: 267
          enable_trg_cmd: "Enabled"
          enable_ch_cmd: "Enabled"

      cfg_goose_off:
        desc: "Goose off"
        ch1:
          operation: "NOOP"
        ch3:
          operation: "NOOP"
        ch5:
          operation: "NOOP"

    goose_arrival_configs:
      desc: "Goose Arrival"
      cfg_early:
        desc: "Early"
        ch0:
          polarity: 1
          width_setpoint: 30.8
        ch2:
          polarity: 1
          width_setpoint: 30.8
        ch4:
          polarity: 1
          width_setpoint: 30.8
      cfg_late:
        desc: "Late"
        ch0:
          polarity: 0
          width_setpoint: 15.4
        ch2:
          polarity: 0
          width_setpoint: 15.4
        ch4:
          polarity: 0
          width_setpoint: 15.4

#  bay_3:
#
#    laser_desc: "Bay 3 TPR Configuration"
#
#    tpr_base: "LAS:LHN:TPR:01"
#
#    # TPR Channels
#    channels:
#      ch0:
#        desc: "Carbide Goose"
#        ch: "00"
#        show: True
#      ch1:
#        desc: "Carbide"
#        ch: "01"
#        show: True
#      ch2:
#        desc: "Amphos Goose"
#        ch: "02"
#        show: True
#      ch3:
#        desc: "Amphos Base"
#        ch: "03"
#        show: True
#      ch4:
#        desc: "Carbide PP Goose"
#        ch: "04"
#        show: True
#      ch5:
#        desc: "Carbide PP"
#        ch: "05"
#        show: True
#      ch6:
#        desc: "TIC Stop Trigger"
#        ch: "06"
#        show: True
#      ch7:
#        desc: "TIC Gate Trigger"
#        ch: "07"
#        show: True
#
#    # Allowed rep-rate configs (in TPG seconds) for the given laser
#    rate_configs:
#      cfg_130:
#        desc: "130 Hz"
#        ch4:
#          ratemode: "Seq"
#          seqcode: 256
#          enable_trg_cmd: "Enabled"
#          enable_ch_cmd: "Enabled"
#        ch5:
#          ratemode: "Seq"
#          seqcode: 256
#          enable_trg_cmd: "Enabled"
#          enable_ch_cmd: "Enabled"
#        ch7:
#          ratemode: "Seq"
#          seqcode: 256
#          enable_trg_cmd: "Enabled"
#          enable_ch_cmd: "Enabled"
#
#      cfg_500:
#        desc: "500 Hz"
#        ch4:
#          ratemode: "Seq"
#          seqcode: 257
#          enable_trg_cmd: "Enabled"
#          enable_ch_cmd: "Enabled"
#        ch5:
#          ratemode: "Seq"
#          seqcode: 257
#          enable_trg_cmd: "Enabled"
#          enable_ch_cmd: "Enabled"
#        ch7:
#          ratemode: "Seq"
#          seqcode: 257
#          enable_trg_cmd: "Enabled"
#          enable_ch_cmd: "Enabled"
#
#      cfg_650:
#        desc: "650 Hz"
#        ch4:
#          ratemode: "Seq"
#          seqcode: 258
#          enable_trg_cmd: "Enabled"
#          enable_ch_cmd: "Enabled"
#        ch5:
#          ratemode: "Seq"
#          seqcode: 258
#          enable_trg_cmd: "Enabled"
#          enable_ch_cmd: "Enabled"
#        ch7:
#          ratemode: "Seq"
#          seqcode: 258
#          enable_trg_cmd: "Enabled"
#          enable_ch_cmd: "Enabled"
#
#      cfg_1300:
#        desc: "1300 Hz"
#        ch4:
#          ratemode: "Seq"
#          seqcode: 259
#          enable_trg_cmd: "Enabled"
#          enable_ch_cmd: "Enabled"
#        ch5:
#          ratemode: "Seq"
#          seqcode: 259
#          enable_trg_cmd: "Enabled"
#          enable_ch_cmd: "Enabled"
#        ch7:
#          ratemode: "Seq"
#          seqcode: 259
#          enable_trg_cmd: "Enabled"
#          enable_ch_cmd: "Enabled"
#
#      cfg_2500:
#        desc: "2500 Hz"
#        ch4:
#          ratemode: "Seq"
#          seqcode: 260
#          enable_trg_cmd: "Enabled"
#          enable_ch_cmd: "Enabled"
#        ch5:
#          ratemode: "Seq"
#          seqcode: 260
#          enable_trg_cmd: "Enabled"
#          enable_ch_cmd: "Enabled"
#        ch7:
#          ratemode: "Seq"
#          seqcode: 260
#          enable_trg_cmd: "Enabled"
#          enable_ch_cmd: "Enabled"
#
#      cfg_8125:
#        desc: "8125 Hz"
#        ch4:
#          ratemode: "Seq"
#          seqcode: 261
#          enable_trg_cmd: "Enabled"
#          enable_ch_cmd: "Enabled"
#        ch5:
#          ratemode: "Seq"
#          seqcode: 261
#          enable_trg_cmd: "Enabled"
#          enable_ch_cmd: "Enabled"
#        ch7:
#          ratemode: "Seq"
#          seqcode: 261
#          enable_trg_cmd: "Enabled"
#          enable_ch_cmd: "Enabled"
#
#      cfg_32500:
#        desc: "32500 Hz"
#        ch4:
#          ratemode: "Seq"
#          seqcode: 262
#          enable_trg_cmd: "Enabled"
#          enable_ch_cmd: "Enabled"
#        ch5:
#          ratemode: "Seq"
#          seqcode: 262
#          enable_trg_cmd: "Enabled"
#          enable_ch_cmd: "Enabled"
#        ch7:
#          ratemode: "Seq"
#          seqcode: 262
#          enable_trg_cmd: "Enabled"
#          enable_ch_cmd: "Enabled"
#
#      cfg_goose_4:
#        desc: "4 Hz Goose"
#        ch0:
#          ratemode: "Seq"
#          seqcode: 264
#          polarity: 0
#          enable_trg_cmd: "Enabled"
#          enable_ch_cmd: "Enabled"
#          width_setpoint: 15.4
#        ch1:
#          operation: "AND"
#        ch2:
#          ratemode: "Seq"
#          seqcode: 264
#          polarity: 0
#          enable_trg_cmd: "Enabled"
#          enable_ch_cmd: "Enabled"
#          width_setpoint: 15.4
#        ch3:
#          operation: "AND"
#        ch4:
#          ratemode: "Seq"
#          seqcode: 264
#          polarity: 0
#          enable_trg_cmd: "Enabled"
#          enable_ch_cmd: "Enabled"
#          width_setpoint: 15.4
#        ch5:
#          operation: "AND"
#        ch7:
#          ratemode: "Seq"
#          seqcode: 264
#          enable_trg_cmd: "Enabled"
#          enable_ch_cmd: "Enabled"
#
#      cfg_goose_40:
#        desc: "40 Hz Goose"
#        ch0:
#          ratemode: "Seq"
#          seqcode: 265
#          polarity: 0
#          enable_trg_cmd: "Enabled"
#          enable_ch_cmd: "Enabled"
#          width_setpoint: 15.4
#        ch1:
#          operation: "AND"
#        ch2:
#          ratemode: "Seq"
#          seqcode: 265
#          polarity: 0
#          enable_trg_cmd: "Enabled"
#          enable_ch_cmd: "Enabled"
#          width_setpoint: 15.4
#        ch3:
#          operation: "AND"
#        ch4:
#          ratemode: "Seq"
#          seqcode: 265
#          polarity: 0
#          enable_trg_cmd: "Enabled"
#          enable_ch_cmd: "Enabled"
#          width_setpoint: 15.4
#        ch5:
#          operation: "AND"
#        ch7:
#          ratemode: "Seq"
#          seqcode: 265
#          enable_trg_cmd: "Enabled"
#          enable_ch_cmd: "Enabled"
#
#      cfg_goose_50:
#        desc: "50 Hz Goose"
#        ch0:
#          ratemode: "Seq"
#          seqcode: 266
#          polarity: 0
#          enable_trg_cmd: "Enabled"
#          enable_ch_cmd: "Enabled"
#          width_setpoint: 15.4
#        ch1:
#          operation: "AND"
#        ch2:
#          ratemode: "Seq"
#          seqcode: 266
#          polarity: 0
#          enable_trg_cmd: "Enabled"
#          enable_ch_cmd: "Enabled"
#          width_setpoint: 15.4
#        ch3:
#          operation: "AND"
#        ch4:
#          ratemode: "Seq"
#          seqcode: 266
#          polarity: 0
#          enable_trg_cmd: "Enabled"
#          enable_ch_cmd: "Enabled"
#          width_setpoint: 15.4
#        ch5:
#          operation: "AND"
#        ch7:
#          ratemode: "Seq"
#          seqcode: 266
#          enable_trg_cmd: "Enabled"
#          enable_ch_cmd: "Enabled"
#
#      cfg_goose_250:
#        desc: "250 Hz Goose"
#        ch0:
#          ratemode: "Seq"
#          seqcode: 267
#          polarity: 0
#          enable_trg_cmd: "Enabled"
#          enable_ch_cmd: "Enabled"
#          width_setpoint: 15.4
#        ch1:
#          operation: "AND"
#        ch2:
#          ratemode: "Seq"
#          seqcode: 267
#          polarity: 0
#          enable_trg_cmd: "Enabled"
#          enable_ch_cmd: "Enabled"
#          width_setpoint: 15.4
#        ch3:
#          operation: "AND"
#        ch4:
#          ratemode: "Seq"
#          seqcode: 267
#          polarity: 0
#          enable_trg_cmd: "Enabled"
#          enable_ch_cmd: "Enabled"
#          width_setpoint: 15.4
#        ch5:
#          operation: "AND"
#        ch7:
#          ratemode: "Seq"
#          seqcode: 267
#          enable_trg_cmd: "Enabled"
#          enable_ch_cmd: "Enabled"
#
#      cfg_goose_off:
#        desc: "Goose off"
#        ch1:
#          operation: "NOOP"
#        ch3:
#          operation: "NOOP"
#        ch5:
#          operation: "NOOP"
