# Configuration file for NEH OPCPA lasers

main:
    xpm_pv: "DAQ:NEH:XPM:0:SEQCODES"
    title: "NEH Laser Hall OPCPA Rep. Rate Configuration"

lasers:
    laser1: "bay_2"

# TODO: add inclusivity PV
bay_2:

  laser_desc: "Bay 2 TPR Configuration"

  tpr_base: "LAS:LHN:TPR:02"

  # TPR Channels
  channels:
    ch1:
      desc: "Carbide"
      ch: "03"
    ch2:
      desc: "Amphos"
      ch: "04"
    ch3:
      desc: "Pulse Picker"
      ch: "05"
    ch4:
      desc: "TIC Trigger"
      ch: "06"
    ch5:
      desc: "Goose Trigger"
      ch: "07"

  # Reprate (in TPG seconds) to event code mapping for the system
  rep_rates:
    130: 256
    260: 257
    500: 258
    1300: 259
    2500: 260
    6500: 261
    8125: 262
    16250: 263
    32500: 264
    910000: 265

  # Allowed rep-rate configs (in TPG seconds) for the given laser
  rate_configs:
    cfg_1300:
      rate: "1300 Hz"
      ch1:
        ratemode: "Fixed"
        rate: "1MHz" 
        enable: "Enabled"
      ch2:
        ratemode: "Seq"
        rate: 1300 
        enable: "Enabled"
      ch3:
        ratemode: "Seq"
        rate: 1300
        enable: "Enabled"
  
    cfg_32500:
      rate: "32500 Hz"
      ch1:
        ratemode: "Fixed"
        rate: "1MHz" 
        enable: "Enabled"
      ch2:
        ratemode: "Seq"
        rate: 32500 
        enable: "Enabled"
      ch3:
        ratemode: "Seq"
        rate: 32500
        enable: "Enabled"
  
    cfg_130:
      rate: "130 Hz"
      ch1:
        ratemode: "Fixed"
        rate: "1MHz" 
        enable: "Enabled"
      ch2:
        ratemode: "Seq"
        rate: 130 
        enable: "Enabled"
      ch3:
        ratemode: "Seq"
        rate: 130
        enable: "Enabled"
  
    cfg_260:
      rate: "260 Hz"
      ch1:
        ratemode: "Fixed"
        rate: "1MHz" 
        enable: "Enabled"
      ch2:
        ratemode: "Seq"
        rate: 260 
        enable: "Enabled"
      ch3:
        ratemode: "Seq"
        rate: 260 
        enable: "Enabled"
  
    cfg_500: 
      rate: "500 Hz"
      ch1:
        ratemode: "Fixed"
        rate: "1MHz" 
        enable: "Enabled"
      ch2:
        ratemode: "Seq"
        rate: 500 
        enable: "Enabled"
      ch3:
        ratemode: "Seq"
        rate: 500 
        enable: "Enabled"



